### ISSUE TITLE
binascii has no attribute a2b_hqx

### ISSUE THREAD

**Issue by halian** [elliotnunn/tbxi#1]
When attempting to dump a binhexed ROM, I get the following error:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\<REDACTED>\AppData\Roaming\Python\Python312\Scripts\tbxi.exe\__main__.py", line 7, in <module>
  File "C:\Users\<REDACTED>\AppData\Roaming\Python\Python312\site-packages\tbxi\__main__.py", line 63, in main
    hb = binhex.HexBin(f)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\<REDACTED>\AppData\Roaming\Python\Python312\site-packages\tbxi\binhex.py", line 371, in __init__
    self._readheader()
  File "C:\Users\<REDACTED>\AppData\Roaming\Python\Python312\site-packages\tbxi\binhex.py", line 389, in _readheader
    len = self._read(1)
          ^^^^^^^^^^^^^
  File "C:\Users\<REDACTED>\AppData\Roaming\Python\Python312\site-packages\tbxi\binhex.py", line 374, in _read
    data = self.ifp.read(len)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\<REDACTED>\AppData\Roaming\Python\Python312\site-packages\tbxi\binhex.py", line 307, in read
    self._fill(wtd - len(self.post_buffer))
  File "C:\Users\<REDACTED>\AppData\Roaming\Python\Python312\site-packages\tbxi\binhex.py", line 313, in _fill
    self.pre_buffer = self.pre_buffer + self.ifp.read(wtd + 4)
                                        ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<REDACTED>\AppData\Roaming\Python\Python312\site-packages\tbxi\binhex.py", line 279, in read
    decdatacur, self.eof = binascii.a2b_hqx(data)
                           ^^^^^^^^^^^^^^^^
AttributeError: module 'binascii' has no attribute 'a2b_hqx'. Did you mean: 'a2b_hex'?
```

**Comment by elliotnunn** [comment]
Hi! This is frustrating. Python deprecated and removed the binhex package, so I just copied it into the repo, but now supporting functions in the binascii package have been removed too. Worse, they were implemented in C. I think I should probably just remove BinHex support -- what do you think?

**Comment by halian** [comment]
I'd prefer having BinHex support, as I don't currently have any working computers that can run classic Mac OS.

**Comment by zahlman** [comment]
The supporting C code was deprecated at the same time (in 3.9) as the `binhex` interface, and removed at the same time (in 3.11) following the usual deprecation cycle. The original rationale for deprecation is given at https://github.com/python/cpython/issues/83534. (This notably preceded the much more aggressive removal of "dead batteries" described in [PEP 594](https://peps.python.org/pep-0594/).)

When that functionality was originally *added* to the standard library (the historical records are sparse, but by checking some copyright and publication dates I guess this was in 1.3), it was in a fundamentally different era regarding the philosophy of what the Python standard library would need, as well as a fundamentally different environment with differing relative popularity of file formats. Nothing lasts forever; the code in question lasted 27 years, which for comparison is almost as long as the time between the first publication of the ASCII standard and the first publication of the Unicode standard.

And I couldn't find any existing third-party support either. Searches for `hqx` anywhere are dominated by stuff about some AI image-scaling algorithm; the only relevant things I found on PyPI were your own projects.

So for a niche project like this I think you'd really have to include it yourself. (I appreciate that things like this exist!) You could require an older Python version in the project metadata, but 3.10 will be EOL in less than a year. Assuming that you aren't interested in introducing C code to the project, I imagine the sensible thing would be to introduce a wrapper to `try` to use the standard library `binhex` (since it will be present whenever `binascii` includes the needed bits), and fall back to included Python code (including patches to implement the missing bits).

It seems to me like it wouldn't take a lot of Python to implement the needed pieces and I'd be interested in submitting a PR if you like the idea. However, presumably the same issue also affects e.g. [your "macresources" project](https://github.com/elliotnunn/macresources) so maybe it would be better to factor out a common dependency? In that situation, no wrappers would be necessary — just a dependency specification in `pyproject.toml` along the lines of `binhex_legacy ; python_version >= 3.11`.

**Comment by elliotnunn** [comment]
Zahlman, thank you for your candid comment. I appreciate that you are willing to put in the work to restore BinHex support, and I would welcome any pull request.

The BinHex format is fairly simple. A pure Python reader/writer should be fast enough.

And as for adding the same support to macresources, I don't mind a little code duplication.

**Comment by zahlman** [comment]
I have some code written now, but it's entirely untested. I don't suppose you have any suitable test data lying around?

**Comment by elliotnunn** [comment]
[binhexes.zip](https://github.com/user-attachments/files/23842749/binhexes.zip)

Small selection of BinHex files from Macintosh Garden

**Comment by zahlman** [comment]
Testing showed that I was quite a bit sloppier than I thought (despite my best efforts), but fixing the problems was fairly straightforward. Hope the PR suits your needs, at least for now.
